######################################################################
# Automatically generated by qmake (3.0) dv. nov. 3 15:37:48 2017
######################################################################

TEMPLATE = app
TARGET = 01-HelloWorld
INCLUDEPATH += .

# Input
SOURCES += hello.cpp

QT += widgets
