######################################################################
# Automatically generated by qmake (3.0) dt. nov. 7 16:07:57 2017
######################################################################

TEMPLATE = app
TARGET = 05-FindDialog
INCLUDEPATH += .

# Input
HEADERS += dialogo.h
SOURCES += dialogo.cpp main.cpp
QT += widgets
