######################################################################
# Automatically generated by qmake (3.0) dv. nov. 3 16:08:42 2017
######################################################################

TEMPLATE = app
TARGET = 02-Conections
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
QT += widgets 
