######################################################################
# Automatically generated by qmake (3.0) dv. nov. 3 16:31:03 2017
######################################################################

TEMPLATE = app
TARGET = 03-LayoutWidgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
