######################################################################
# Automatically generated by qmake (3.0) dt. nov. 14 17:38:38 2017
######################################################################

TEMPLATE = app
TARGET = calculator
INCLUDEPATH += .

# Input
HEADERS += calculator.h
FORMS += calculator.ui DialogoRed.ui
SOURCES += calculator.cpp main.cpp
QT += widgets
