######################################################################
# Automatically generated by qmake (3.0) dv. nov. 10 17:43:33 2017
######################################################################

TEMPLATE = app
TARGET = calculator
INCLUDEPATH += .

# Input
HEADERS += calculator.h ui_calculator.h
FORMS += calculator.ui
SOURCES += main.cpp
QT += widgets
