######################################################################
# Automatically generated by qmake (3.0) dv. nov. 10 16:58:38 2017
######################################################################

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
QT += widgets
