######################################################################
# Automatically generated by qmake (2.01a) vie ene 12 12:48:20 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Bola.h MainWindow.h
SOURCES += Bola.cpp main.cpp MainWindow.cpp
QT += widgets
