######################################################################
# Automatically generated by qmake (3.0) dt. gen. 9 15:47:22 2018
######################################################################

TEMPLATE = app
TARGET = bolas
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
QT += widgets
