######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 12 17:07:50 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Bola.h DInformacion.h MainWindow.h
FORMS += DInformacion.ui
SOURCES += Bola.cpp DInformacion.cpp main.cpp MainWindow.cpp
QT += widgets
