######################################################################
# Automatically generated by qmake (3.0) dt. des. 12 16:49:20 2017
######################################################################

TEMPLATE = app
TARGET = Editor
INCLUDEPATH += .

# Input
HEADERS += dialogodeshacer.h finddialog.h mainwindow.h
FORMS += dialogodeshacer.ui
SOURCES += dialogodeshacer.cpp finddialog.cpp main.cpp mainwindow.cpp
QT += widgets
