######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 21 14:36:58 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
QT += widgets
